[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ontobdc"
authors = [{ name="Elias M P Junior" }]
version = "0.1.0a0"
description = "OntoBDC"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "PyYAML",
    "numpy",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["ontobdc*"]
