[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ontobdc"
authors = [{ name="Elias M P Junior" }]
version = "0.1.0a1"
description = "OntoBDC"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "PyYAML",
    "numpy",
]

[project.scripts]
ontobdc = "ontobdc.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"ontobdc" = [
    "*.sh",
    "cli/*.sh",
    "dev/*.sh",
    "run/*.sh",
    "check/infra/*.sh",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["ontobdc*"]
