[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ontobdc"
version = "0.0.1"
description = "OntoBDC"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "PyYAML",
    "numpy",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["ontobdc.tmp*"]
